### ISSUE TITLE
vcfbub installation/usage

### ISSUE THREAD

**Issue by lsoldini** [pangenome/vcfbub#1]
Hello to all, 

I am struggling with `vcfbub` installation. I've looked for documentation but could not find something that helped me through it (I should point out that I am a biologist and may as well be missing something quite straightforward).  

I first thought that `vcfbub` may be integrated in another pangenome tool (I looked in `pggb`, `vg`,  `vcflib`), but did not find it. 

I then tried to copy the git repository, but this led me to the conclusion that I require rust with cargo to run the `main.rs` file. For some reason, the `rust` installation is not working (neither locally nor on the hpc cluster I am using). 

How should I proceed to be able to use `vcfbub` ? Should I keep trying with rust installation or is there another way ? 

Thank you for your time on this issue. 

Best, 
Luca Soldini

**Comment by ekg** [comment]
I believe it's: cargo install --force .

This is pretty standard for rust projects. I'll add a note about the build
process

**Comment by lsoldini** [comment]
Thank you, I'll look more into rust then.

Edit: this worked for me
1) `git clone https://github.com/pangenome/vcfbub.git`
2) `cd vcfbub`
3) `cargo install --path . --root /path/to/folder` 
4) `~/path/to/folder/bin/vcfbub -i file.vcf etc.`
