### ISSUE TITLE
Rust Error occurs:{ kind: InvalidInput, error: "invalid gzip header" }

### ISSUE THREAD

**Issue by Zoeyoungxy** [pangenome/vcfbub#5]
Hi there,
I met the Rust error. The command is
`vcfbub  -l 0 -r 100000 -i input.vcf > output.filter.vcf`

I got the error message like:
'thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: InvalidInput, error: "invalid gzip header" })', src/main.rs:14:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace'

The graph was built using MC, and the input.vcf file was generated using the command `vg deconstruct`.

I am not familiar with this error message. Is there anything with my vcf file? I wonder how to check the vcf file in advance or is there any methods to deal with the problem?

Any help will be highly appreciated.

Thank You!
-Zoey

**Comment by AndreaGuarracino** [comment]
`vcfbub` requires a gzipped VCF file as input. Run:

```bash
gzip input.vcf
vcfbub -l 0 -r 100000 -i input.vcf.gz > output.filter.vcf
```

**Comment by Zoeyoungxy** [comment]
> `vcfbub` requires a gzipped VCF file as input. Run:
> 
> ```shell
> gzip input.vcf
> vcfbub -l 0 -r 100000 -i input.vcf.gz > output.filter.vcf
> ```

OK, I'll try soon. Thanks a lot.
